### ISSUE TITLE
9.0.2.27 through 9.0.2.29 missing from CurseForge

### ISSUE THREAD

**Issue by layday** [Twintop/TwintopInsanityBar#102]
Hi @Twintop, I don't know if you've yanked the three latest releases but they are no longer available from CurseForge.  I was a little surprised to see my add-on manager update TIB from `9.0.2.28-release` to `9.0.2.26-release` :)

**Comment by Twintop** [comment]
Hey layday,

Thanks for opening an issue!

This was done on purpose a few minutes ago. I archived 9.0.2.27-release and 9.0.2.28-release from CurseForge because there is a pretty nasty LUA bug involving Searing Nightmare in those versions. This is fixed in 9.0.2.29-release, but it has been sitting in Overwolf's review queue for nearly 24 hours as "Under Review".

Since it's a fresh week of M0s, I decided to err on the side of caution and issue a rollback since the only loss of functionality is Marksmanship Hunter (which sucks), plus, Wrathful Faerie+Fermata and Rabid Shadows for Shadow Priest.

Starting with 9.0.2.30-release I'm going to start listing WoWInterface as the primary source in the TOC to avoid Overwolf issues in the future, so at least if people are using something like WowUp they'll still get the latest version.

I'm going to leave this open so others can see this bug if they have concerns as well.

Cheers!

**Comment by layday** [comment]
Thanks for explaining.  CF is undergoing migration to OW's infra until 3 Dec so I think it might sit in the queue for a little while longer.  Out of curiosity, how do you specify a primary source in the TOC?

**Comment by Twintop** [comment]
I did some looking at other projects to see how they manage it and settled on this:
https://github.com/Twintop/TwintopInsanityBar/commit/bfa15a84a00dc5a2c90c3ea95269a9bd477b09b0

Essentially there are `X-` metadata entries you can add that aren't used by WoW but can be used by other things, like addon managers. (https://wow.gamepedia.com/TOC_format#Informational)

WowUp has an open issue about adding more support for this (https://github.com/WowUp/WowUp/issues/552), which links to their FAQ on it (https://wowup.io/guide/section/my-addons/addons , Multiple Providers). So I added the following:
```
## X-Curse-Project-ID: 293075
## X-WoWI-ID: 24628
```
WowUp then should look at Curse first for the addon, but also list WoWInterface as a secondary source. If I reverse these lines then WowUp should switch to looking at WoWInterface first.

**Comment by layday** [comment]
By default, WowUp will attempt to find a matching add-on on CurseForge by hashing the add-on's contents - what's called fingerprinting.  If it's not able to find a match, only then will it fall back on TOC IDs.  I'm not sure if the order will have an effect, or if it does, that behaviour is specific to WowUp and might not even be intentional.

For a bit of history, I believe TOC IDs originate from [packager](https://github.com/BigWigsMods/packager).  The idea was to automate uploading add-ons to CF and WoWI without having to pass the ID in the command line.  They were repurposed by add-on managers for reconciliation.

**Comment by Twintop** [comment]
That's great context to be aware of. I was curious where these specific `X-` metadata came from!

How do you handle situations like this in instawow? Like, take TRB for example right now: Curse says .26-release is latest, .28-release is what you have, but WoWI has .29-release. What would it prefer, or how could I make it prefer one source of truth over another?

**Comment by layday** [comment]
In instawow, reconciliation is a one-time thing and you can go through all of your pre-existing add-ons and select which source you'd like to link them up to.  If you choose to automate reconciliation, it will default to CurseForge because it's generally proven more popular with add-on authors and add-ons on CF see more frequent updates (the current outage aside).  I think that's the case with most add-on managers, that they'll prefer CF.  instawow is slightly unusual in that it lets you pick the source.  Off the top of my head:

* WowUp and Ajour use fingerprinting, which only works with CurseForge, and TOC IDs if that fails
* instawow and CurseBreaker use TOC IDs or folder names, prioritising CF
* strongbox uses TOC `Title`s - not sure if it prioritises CF, but it's probably safe to assume that it does

**Comment by layday** [comment]
This is what it looks like in instawow with an add-on which is available from both CF and WoWI:

![rec](https://user-images.githubusercontent.com/31134424/100810885-103f4580-3442-11eb-839e-41c2edba7361.gif)

**Comment by layday** [comment]
Looks like 9.0.2.29 has been accepted if you want to close this now :)

**Comment by Twintop** [comment]
Woo! Thanks for letting me know! :D
