### ISSUE TITLE
"BOOM" Spamming Chat

### ISSUE THREAD

**Issue by Aimsucks** [Twintop/TwintopInsanityBar#103]
There seems to be a print [here](https://github.com/Twintop/TwintopInsanityBar/blob/b41fa6cb4d4c038ea996425ad2741a5acbfdce23/Classes/Hunter.lua#L943) that is causing BOOM to spam chat when I cast Explosive Shot. Is there any way to remove this in the options? I couldn't find anything. I am open to doing a quick PR to make this easier for you.

**Comment by Twintop** [comment]
Ah, yikes. I know exactly what this is -- left over debug code from Marksmanship development. I'll clean that up and include a fix in the next release (probably tonight). Thanks for the report!
