### ISSUE TITLE
LUA error with latest version and broken options menu.

### ISSUE THREAD

**Issue by Daervon** [Twintop/TwintopInsanityBar#121]
I've been getting the following error with the latest version of the addon. The bar still seems to work, however there are certain elements in the options menu that don't:

For example, in the Options menu --> Shadow Priest options --> Bar Display tab: Can't scroll down beyond the title "Ability Threshold Lines". Also, the other tabs (Font & Text, Audio & Tracking, Bar Text, Reset Defaults) are all empty when I switch to them.

I tried with only this addon, BugSack and BugGrabber enabled and the error persisted, along with the other issues in the options menu, so it doesn't seem to be a conflict with something else.

1x TwintopInsanityBar\Classes\PriestOptions.lua:1317: attempt to index field 'colors' (a nil value)
[string "@TwintopInsanityBar\Classes\PriestOptions.lua"]:1317: in function <TwintopInsanityBar\Classes\PriestOptions.lua:462>
[string "@TwintopInsanityBar\Classes\PriestOptions.lua"]:3219: in function <TwintopInsanityBar\Classes\PriestOptions.lua:3163>
[string "@TwintopInsanityBar\Classes\PriestOptions.lua"]:3228: in function `ConstructOptionsPanel'
[string "@TwintopInsanityBar\Classes\Priest.lua"]:2457: in function <TwintopInsanityBar\Classes\Priest.lua:2439>

Locals:
parent = <unnamed> {
 0 = <userdata>
 CheckButton = TIBCB1_5 {
 }
}
interfaceSettingsFrame = <table> {
 panel = TwintopResourceBarPanel {
 }
 shadowDisplayPanel = TwintopResourceBar_Options_Priest_Shadow {
 }
 controls = <table> {
 }
 optionsPanel = TwintopResourceBar_Options_General {
 }
}
controls = <table> {
 textSection = <unnamed> {
 }
 ttdPrecision = <unnamed> {
 }
 vertical = <unnamed> {
 }
 textbox = <table> {
 }
 barColorsSection = <unnamed> {
 }
 thresholdWidth = <unnamed> {
 }
 ttdSamplingRate = <unnamed> {
 }
 flashPeriod = <unnamed> {
 }
 textBarTexturesSection = <unnamed> {
 }
 flashAlpha = <unnamed> {
 }
 colors = <table> {
 }
 characterRefreshRate = <unnamed> {
 }
 borderWidth = <unnamed> {
 }
 width = <unnamed> {
 }
 barDisplaySection = <unnamed> {
 }
 ttdSampleSize = <unnamed> {
 }
 checkBoxes = <table> {
 }
 dropDown = <table> {
 }
 height = <unnamed> {
 }
 horizontal = <unnamed> {
 }
 barPositionSection = <unnamed> {
 }
 labels = <table> {
 }
}
yCoord = -820
f = <unnamed> {
 0 = <userdata>
 Font = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 backdropInfo = <table> {
 }
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 RightEdge = <unnamed> {
 }
 Texture = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
}
maxOptionsWidth = 580
xPadding = 10
xPadding2 = 30
xCoord = 5
xCoord2 = 290
xOffset1 = 50
xOffset2 = 340
title = "Devouring Plague Flash Period (sec)"
dropdownWidth = 225
sliderWidth = 260
sliderHeight = 20
maxBorderHeight = 4
(*temporary) = <table> {
 borderOvercap = <unnamed> {
 }
 enterVoidform = <unnamed> {
 }
 border = <unnamed> {
 }
 inVoidform1GCD = <unnamed> {
 }
 inVoidform = <unnamed> {
 }
 passive = <unnamed> {
 }
 casting = <unnamed> {
 }
 base = <unnamed> {
 }
 background = <unnamed> {
 }
}
(*temporary) = <function> defined @TwintopInsanityBar\UiFunctions.lua:199
(*temporary) = <unnamed> {
 0 = <userdata>
 CheckButton = TIBCB1_5 {
 }
}
(*temporary) = "Under minimum required Insanity"
(*temporary) = nil
(*temporary) = <table> {
 core = <table> {
 }
 druid = <table> {
 }
 shaman = <table> {
 }
 priest = <table> {
 }
 hunter = <table> {
 }
}
(*temporary) = <unnamed> {
 0 = <userdata>
 font = <unnamed> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "Ability Threshold Lines"
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = "attempt to index field 'colors' (a nil value)"
TRB = <table> {
 Options = <table> {
 }
 Functions = <table> {
 }
 Details = <table> {
 }
 UiFunctions = <table> {
 }
 Frames = <table> {
 }
 Data = <table> {
 }
}
barContainerFrame = TwintopResourceBarFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined

**Comment by Twintop** [comment]
Thanks for reporting this, Daervon! There was some copypasta fails afoot that would only impact players who haven't used the bar on a Hunter. The next release (very soon) should fix this. :)
