### ISSUE TITLE
Hunter Focus loss from hardcasting spell rapidfire 

### ISSUE THREAD

**Issue by JonasLiebe** [Twintop/TwintopInsanityBar#126]
When hardcasting Aimed Shot -> Rapid Fire (Spellqueued), prediction color and prediction text assume Rapid Fire costs focus. 
Only happens when the Rapid Fire ist spellqueued and directly after the Aimed Shot.
https://gyazo.com/73ace2efd64aa70dc3d132db8b3e2a97

**Comment by Twintop** [comment]
Thanks for reporting this @JonasLiebe! I've got a fix that should solve this and a few other similar behaviors that could pop up.
