### ISSUE TITLE
9.1: lua errors when targeting self (Shadow Priest)

### ISSUE THREAD

**Issue by Daervon** [Twintop/TwintopInsanityBar#169]
As the title says... I was in my covenant playing with the dummies when I decided to target myself and have a dummy as focus. Then all hell broke loose in BugSack. I tested it with no focus target as well, same thing. No need to be casting anything or be in combat. As soon as I have my player targeted, the errors start.
Does not seem tied to Insanity levels either -- tested with both empty Insanity and full/ticking down.

435x TwintopInsanityBar\Init.lua:85: attempt to index field '?' (a nil value)
[string "@TwintopInsanityBar\Init.lua"]:85: in function `onUpdate'
[string "@TwintopInsanityBar\Classes\Priest.lua"]:1433: in function <TwintopInsanityBar\Classes\Priest.lua:1433>

Locals:
self = <unnamed> {
 0 = <userdata>
 ttdSinceLastUpdate = 0.207000
 sinceLastUpdate = 0.015000
 characterCheckSinceLastUpdate = 0.796000
 onUpdate = <function> defined @TwintopInsanityBar\Init.lua:51
}
sinceLastUpdate = 0.015000
currentTime = 49722.905000
guid = "Player-3676-0A467BC5"
currentTime = 49722.905000
isDead = false
currentHealth = 39240
maxHealth = 39240
healthDelta = 0
timeDelta = 0
dps = 0
ttd = 0
(*temporary) = <function> defined @TwintopInsanityBar\Functions.lua:7
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
TRB = <table> {
 Options = <table> {
 }
 Functions = <table> {
 }
 Details = <table> {
 }
 UiFunctions = <table> {
 }
 Frames = <table> {
 }
 Data = <table> {
 }
}

**Comment by Twintop** [comment]
Hey Daervon, thanks for reporting this! Oversight from my other changes in 9.1.0.2-release. A new version should be available to download once OW/WoWI pick it up. Cheers!
