### ISSUE TITLE
Darkglare Boon/Medallion support

### ISSUE THREAD

**Issue by Tyraendiel** [Twintop/TwintopInsanityBar#182]
Support extended time remainging on Metamorphosis buff from multiple Eye Beam or Fel Devastation procs thanks to Darkglare Boon legendary or the Thorgast anima power variant Darkglare Medallion. (https://www.wowhead.com/spell=337534/darkglare-boon) (https://www.wowhead.com/spell=322832/darkglare-medallion)

**Comment by Twintop** [comment]
Thanks for reporting this, @Tyraendiel! I've got a fix in that should account for not only Darkglare Boon and Darkglare Medallion but also the Demonic talent. I don't currently have an easy way to test this thoroughly, unfortunately, so please let me know if the issue persists after 9.1.0.11-release comes out shortly. Cheers!

**Comment by Tyraendiel** [comment]
Thanks for the info, I definitely will test it, and report the result.

David C. Uhrig ***@***.***> (időpont: 2021. aug. 7., Szo,
8:03) ezt írta:

**Comment by Twintop** [comment]
Correction: this will be in **9.1.0.11-release** which is coming in a few minutes. Thanks!

**Comment by Tyraendiel** [comment]
It works like a charm. Thank you!
