### ISSUE TITLE
'Pulsar collected' throwing errors when legendary item is equipped, but no buffs appear 

### ISSUE THREAD

**Issue by R1PLI** [Twintop/TwintopInsanityBar#188]
Got the issue when legendary item is equipped, but no buff presents (for some reason), linking the stack-trace below

> Message: ...nterface\AddOns\TwintopInsanityBar\Classes\Druid.lua:1068: attempt to perform arithmetic on local 'pulsarCollected' (a nil value)
Time: Sat Sep  4 20:17:50 2021
Count: 2055
Stack: ...nterface\AddOns\TwintopInsanityBar\Classes\Druid.lua:1068: attempt to perform arithmetic on local 'pulsarCollected' (a nil value)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\TwintopInsanityBar\Classes\Druid.lua"]:1068: in function `RefreshLookupData'
[string "@Interface\AddOns\TwintopInsanityBar\Functions.lua"]:1178: in function `UpdateResourceBar'
[string "@Interface\AddOns\TwintopInsanityBar\Classes\Druid.lua"]:1522: in function <...nterface\AddOns\TwintopInsanityBar\Classes\Druid.lua:1319>
[string "@Interface\AddOns\TwintopInsanityBar\Classes\Druid.lua"]:1538: in function `TriggerResourceBarUpdates'
[string "@Interface\AddOns\TwintopInsanityBar\Init.lua"]:57: in function `onUpdate'
[string "@Interface\AddOns\TwintopInsanityBar\Classes\Druid.lua"]:575: in function <...nterface\AddOns\TwintopInsanityBar\Classes\Druid.lua:575>
Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Comment by Twintop** [comment]
Thanks for reporting this. Getting ready to push out 9.1.0.14-release shortly that should fix this bug. Sorry about that!
