### ISSUE TITLE
WoWInterface add-on zip is malformed

### ISSUE THREAD

**Issue by layday** [Twintop/TwintopInsanityBar#208]
Hi Twintop, happy new year.  Just thought I'd let you know that the add-on zip on WoWInterface does not contain a top-level "TwintopInsanityBar" folder and will (hopefully :) be rejected by add-on managers on install.

**Comment by Twintop** [comment]
Happy New Year! Thank you for letting me know this is an issue, @layday. I'll get a fixed version up in a bit.

**Comment by layday** [comment]
Thanks!
