### ISSUE TITLE
Insanity bar clickthrough

### ISSUE THREAD

**Issue by BartOutOfTheBox** [Twintop/TwintopInsanityBar#22]
**Describe the solution you'd like**
Make an option to make the insanity bar click-through.

**problem?**
My insanity bar has a central place in my UI. Turning in game I usually do by clicking and dragging the mouse. Sometimes I accidentally click on the insanity bar and then nothing happings.

**Comment by Twintop** [comment]
I'm not entirely sure how to make the bar click-through. All of the references I've found to accomplish this (e.g. frame:EnableMouse(false) ) aren't having any effect. If anyone knows how to make this work I'd be grateful.

**Comment by BartOutOfTheBox** [comment]
Maybe this has something to do with it?

"Setting a mouse event handler (OnMouseDown, OnMouseUp and most likely OnClick) using SetScript will automatically set the mouse to enabled."

I haven't looked into the insanity bar's code yet tbh. Got a couple of busy weeks for work right now. I might look into it deeper when I have some more time.
