### ISSUE TITLE
Apex Predator visual indicator

### ISSUE THREAD

**Issue by Niphyr** [Twintop/TwintopInsanityBar#224]
It would be nice if there were a way for Apex Predator's Craving buff (339140) to alter the bar in some way. (Feral Druid Legendary)

![image](https://user-images.githubusercontent.com/1481378/164869484-3bbefc7c-a675-4dcb-95e2-b4f8e72b8383.png)

The way I think makes the most sense is for it to use the "Energy when 5 CP and FB will do max dmg" colour.

![image](https://user-images.githubusercontent.com/1481378/164869522-57229972-51d1-433f-8fa8-a20012e2278c.png)

**Comment by Twintop** [comment]
Looks like this is implemented already but there may be some other issue with detection. Closing for now.

**Comment by Twintop** [comment]
Changing Apex Predator's Craving proc to not use the same "Max Bite" coloring but instead have it's own.
