### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by Tooonfish** [Twintop/TwintopInsanityBar#24]
There seems to be an issue with the color picker, when selecting a color with an R, G or B component less than 16. 

The resulting string will be one character shorter than expected
9, 255, 255 => FF9FFFF instead of something like 16, 255, 255 => FF10FFFF

This apparently confuses the color picker and a wrong color will be picked

I was trying to fix my backdrop to 42, 12, 52 but it would always change back to 42, 100+something, something

I settled with picking 54, 16, 68, which works without any issues

**Comment by Twintop** [comment]
Looks like this is a regression from the 7.x/Legion version to the 8.x/BfA version. I'll forward port the code to fix this. Thanks for letting me know!
