### ISSUE TITLE
Dragonflight Assassination Rogue

### ISSUE THREAD

**Issue by Twintop** [Twintop/TwintopInsanityBar#253]
- [x] Tight Spender
- [x] Improved Garrote notification / color change
- [x] Shiv charges (Lightweight Shiv)
- ~~[ ] Amplifying Poison stacks~~ Will add if requested.
- - ~~Bar text~~
- - ~~Bar notification? Color change/border change/sound when above X?~~
- ~~[ ] Check the behavior of Covenant abilities / conduits and how they stack with talents.~~
- [x] Toggle shading of combo points for Serrated Bone Spike.

**Comment by MaDVitek** [comment]
![image](https://user-images.githubusercontent.com/117979757/207018343-676c9801-3130-4127-9b2a-02cda83e53c5.png)
how can off this?

**Comment by Twintop** [comment]
@MaDVitek There isn't at the moment, but I can add it as a toggle in the next release.
