### ISSUE TITLE
Combat rogue lua error

### ISSUE THREAD

**Issue by MaDVitek** [Twintop/TwintopInsanityBar#260]
Message: ...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:4730: attempt to perform arithmetic on field 'atrophicPoison' (a nil value)
Time: Fri Nov 11 12:08:18 2022
Count: 1
Stack: ...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:4730: attempt to perform arithmetic on field 'atrophicPoison' (a nil value)
[string "@Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua"]:4730: in function <...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:4263>

Locals: self = TwintopResourceBarFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
currentTime = 497171.746000
triggerUpdate = false
_ = nil
specId = 2
time = 1668157698.351000
type = "SPELL_AURA_APPLIED"
_ = false
sourceGUID = "Player-1602-0B8391A2"
sourceName = "Лайсгл"
_ = 1297
_ = 0
destGUID = "Creature-0-4248-2222-12227-65310-00006E1101"
destName = "Тренировочная репа"
_ = 68136
_ = 0
spellId = 392388
spellName = "Атрофический яд"
(*temporary) = <table> {
 numbingPoison = 0
 currentTargetGuid = "Creature-0-4248-2222-12227-65310-00006E1101"
 ttdIsActive = false
 cripplingPoison = 0
 targets = <table> {
 }
 woundPoison = 0
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = true
(*temporary) = 497171.746000
(*temporary) = 497171.746000
(*temporary) = <table> {
}
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'atrophicPoison' (a nil value)"
TRB = <table> {
 Options = <table> {
 }
 Functions = <table> {
 }
 Details = <table> {
 }
 UiFunctions = <table> {
 }
 Frames = <table> {
 }
 Data = <table> {
 }
}
InitializeTarget = <function> defined @Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:1933
CheckCharacter = <function> defined @Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:1804
RefreshTargetTracking = <function> defined @Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:1989
TargetsCleanup = <function> defined @Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:2117
TriggerResourceBarUpdates = <function> defined @Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:4247

And many spam current combo points in chat 15 times in 1 sec.

**Comment by Twintop** [comment]
Hi @MaDVitek, thank you for reporting these issues. I believe I've fixed them (and an additional annoying LUA error when switching specs) now. Please try 10.0.0.14-release and let me know if you run in to any issues. Thanks again!
