### ISSUE TITLE
Echoing Reprimand buff hard to see

### ISSUE THREAD

**Issue by MaDVitek** [Twintop/TwintopInsanityBar#270]
![image](https://user-images.githubusercontent.com/117979757/213473570-f0cd0e0c-8ac4-42e9-a3c7-f2824fc6676a.png)
The border to indicate the buff is enough. Can u make the central zone transparent, like on combo points?

**Comment by Twintop** [comment]
Sure, I'll add it as another configuration option.

**Comment by Twintop** [comment]
@MaDVitek Looking for a bit of clarification: are you asking that Echoing Reprimand buffed CPs that you don't have yet have the fill/styling like an unfilled CP like this:
![image](https://user-images.githubusercontent.com/1485707/213611362-d9d81289-62df-4a27-b00f-f7d82b55a27c.png)

**Comment by MaDVitek** [comment]
yes, its nice on ur screenshot

**Comment by Twintop** [comment]
This will come out with 10.0.5.0-release on reset this week.
