### ISSUE TITLE
Deep Wounds causing LUA errors

### ISSUE THREAD

**Issue by MaDVitek** [Twintop/TwintopInsanityBar#289]
1x TwintopInsanityBar/Classes/Warrior.lua:2110: attempt to perform arithmetic on field 'deepWounds' (a nil value)
[string "@TwintopInsanityBar/Classes/Warrior.lua"]:2110: in function <TwintopInsanityBar/Classes/Warrior.lua:2035>

Locals:
self = TwintopResourceBarFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
currentTime = 587688.273000
triggerUpdate = false
_ = nil
specId = 1
time = 1677160263.712000
type = "SPELL_AURA_APPLIED"
_ = false
sourceGUID = "Player-1602-0EC7781A"
sourceName = "Дестингл"
_ = 1297
_ = 32
destGUID = "Player-1302-0B75F902"
destName = "Salouppio-Archimonde"
_ = 66888
_ = 0
spellId = 262115
spellName = "Глубокие раны"
(*temporary) = <table> {
 rend = 0
 ttdIsActive = false
 targets = <table> {
 }
 currentTargetGuid = "Player-1302-0B75F902"
}
(*temporary) = nil
(*temporary) = "Player-1302-0B75F902"
(*temporary) = nil
(*temporary) = 1
(*temporary) = true
(*temporary) = 587688.273000
(*temporary) = 587688.273000
(*temporary) = <table> {
 rendRemaining = 0
 deepWounds = true
 deepWoundsRemaining = 0
 lastUpdate = 587688.273000
 rend = false
 ttd = 0
 snapshot = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = "Player-1302-0B75F902"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'deepWounds' (a nil value)"
TRB = <table> {
 Options = <table> {
 }
 Functions = <table> {
 }
 Details = <table> {
 }
 Data = <table> {
 }
 Frames = <table> {
 }
}
UpdateBladestorm = <function> defined @TwintopInsanityBar/Classes/Warrior.lua:1526
RefreshTargetTracking = <function> defined @TwintopInsanityBar/Classes/Warrior.lua:919
TargetsCleanup = <function> defined @TwintopInsanityBar/Classes/Warrior.lua:947

**Comment by Twintop** [comment]
I wasn't able to reproduce this but I see how it could occur if things were timed just right (or wrong, in this case). I've put some guardrails in to prevent this.
