### ISSUE TITLE
Overcap bar text variable pulls from Shadow Priest settings not current spec settings

### ISSUE THREAD

**Issue by ghankins** [Twintop/TwintopInsanityBar#307]
1066x TwintopInsanityBar/Classes/Hunter.lua:3887: attempt to index field 'overcap' (a nil value)
[string "@TwintopInsanityBar/Classes/Hunter.lua"]:3887: in function `IsValidVariableForSpec'
[string "@TwintopInsanityBar/Classes/Hunter.lua"]:1668: in function `RefreshLookupData'
[string "@TwintopInsanityBar/Functions/BarText.lua"]:832: in function `UpdateResourceBarText'
[string "@TwintopInsanityBar/Classes/Hunter.lua"]:2812: in function <TwintopInsanityBar/Classes/Hunter.lua:2583>
[string "@TwintopInsanityBar/Classes/Hunter.lua"]:3953: in function `TriggerResourceBarUpdates'
[string "@TwintopInsanityBar/Init.lua"]:91: in function `onUpdate'
[string "@TwintopInsanityBar/Classes/Hunter.lua"]:3699: in function <TwintopInsanityBar/Classes/Hunter.lua:3699>

Locals:
self = <table> {
 IsValidVariableForSpec = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3793
 EventRegistration = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3668
 TriggerResourceBarUpdates = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3942
 InitializeTarget = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3774
 HideResourceBar = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3710
 CheckCharacter = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:3645
}
var = "$overcap"
valid = false
specId = 1
settings = <table> {
 textures = <table> {
 }
 audio = <table> {
 }
 thresholds = <table> {
 }
 displayText = <table> {
 }
 displayBar = <table> {
 }
 overcapThreshold = 120
 colors = <table> {
 }
 generation = <table> {
 }
 hastePrecision = 2
 overcap = <table> {
 }
 bar = <table> {
 }
}
threshold = 100
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'overcap' (a nil value)"
TRB = <table> {
 Options = <table> {
 }
 Functions = <table> {
 }
 Details = <table> {
 }
 Frames = <table> {
 }
 Data = <table> {
 }
}
GetTrueshotRemainingTime = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:1574
GetSteadyFocusRemainingTime = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:1578
GetLockAndLoadRemainingTime = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:1586
GetCoordinatedAssaultRemainingTime = <function> defined @TwintopInsanityBar/Classes/Hunter.lua:1582

**Comment by Twintop** [comment]
Thanks for reporting this, @ghankins ! It should be fixed in 10.1.0.1-release, which is being pushed out to Curse/Wago/WoWI right now. Cheers!

**Comment by ghankins** [comment]
> Thanks for reporting this, @ghankins ! It should be fixed in 10.1.0.1-release, which is being pushed out to Curse/Wago/WoWI right now. Cheers!

Verified that it's fixed in 10.1.0.1.  Thanks for the quick update and for maintaining this AddOn.
