### ISSUE TITLE
Holy Priest - Add small bars for holy words

### ISSUE THREAD

**Issue by Niphyr** [Twintop/TwintopInsanityBar#325]
It would be nice to have smaller bars that can track the cooldown of holy words, including the talent Miracle Worker. Having something similar to combo points where each point is a Holy Word would be great, bonus points if there is an indicator like a colour change if the current cast will take one off cooldown.

For example, there would be 3 "combo points" by default, one for each holy word. Then with Miracle Worker talented, it would expand out to 5. 2 each for Serenity/Sanc, and one for Chastise.

**Comment by Twintop** [comment]
Almost done, here's a snapshot of where it is at the moment.
![image](https://github.com/Twintop/TwintopInsanityBar/assets/1485707/01478b5c-e543-41b2-8a58-27b0177fbc57)
