### ISSUE TITLE
Resource values not updating correctly

### ISSUE THREAD

**Issue by KareiTV** [Twintop/TwintopInsanityBar#407]
The resourcevalues (Eclipsetime on the middle text and Astralpower on the right text) don't update correctly as soon as I reach the first bar of Starsurge. Whenever it's below that value the entire module works perfectly. Any idea what's causing this since this is only noticeable on the Moonkin module. For Shadow and Elemental I have not had this occur.

**Comment by Twintop** [comment]
Thanks for reporting @KareiTV ! This usually happens if there's a Lua error somewhere. If you don't have an easy way of getting the Lua error (assuming there is one), can you instead share your current talent loadout with me, please? Also, if possible, an export of your Balance settings?
<img width="408" alt="image" src="https://github.com/user-attachments/assets/a54156d6-1a8a-42a8-b05a-45cc3870f967">

**Comment by KareiTV** [comment]
**This is the error it generated. Buggrabber was going mental**
 ...nterface/AddOns/TwintopInsanityBar/Functions/Bar.lua:113: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha)) 
[01:06:08] [string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/TwintopInsanityBar/Functions/Bar.lua"]:113: in function `PulseFrame'
[string "@Interface/AddOns/TwintopInsanityBar/ClassModules/Druid.lua"]:2750: in function <...ace/AddOns/TwintopInsanityBar/ClassModules/Druid.lua:2462>
[string "@Interface/AddOns/TwintopInsanityBar/ClassModules/Druid.lua"]:4622: in function `TriggerResourceBarUpdates'
[string "@Interface/AddOns/TwintopInsanityBar/Init.lua"]:226: in function `onUpdate'
[string "@Interface/AddOns/TwintopInsanityBar/ClassModules/Druid.lua"]:3880: in function <...ace/AddOns/TwintopInsanityBar/ClassModules/Druid.lua:3880> 
[01:06:08] (*temporary) = TwintopResourceBarFrame {
 PixelSnapDisabled = true
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
(*temporary) = Infinite

**This is the talent loadout:**

CYGAqvgeoHLefPLb/Pa8nkKXDBAAAAAAAAAAAAAAAAAAQxMzMjZMzAwMmZAzsMwYGzYzMPwMMWmZbmxMYBsAgBAAAAAAAwYYG

**This is the Spec export:**

!TRB!eyJkcnVpZCI6eyJiYWxhbmNlIjp7InRleHR1cmVzIjp7InJlc291cmNlQmFyTmFtZSI6IkFybW9yeSIsImNhc3RpbmdCYXIiOiJJbnRlcmZhY2VcXEFkZG9uc1xcU2hhcmVkTWVkaWFcXHN0YXR1c2JhclxcQXJtb3J5IiwiYm9yZGVyTmFtZSI6Ik5vbmUiLCJib3JkZXIiOiIiLCJ0ZXh0dXJlTG9jayI6dHJ1ZSwiY2FzdGluZ0Jhck5hbWUiOiJBcm1vcnkiLCJwYXNzaXZlQmFyTmFtZSI6IkFybW9yeSIsInBhc3NpdmVCYXIiOiJJbnRlcmZhY2VcXEFkZG9uc1xcU2hhcmVkTWVkaWFcXHN0YXR1c2JhclxcQXJtb3J5IiwiYmFja2dyb3VuZCI6IkludGVyZmFjZVxcVG9vbHRpcHNcXFVJLVRvb2x0aXAtQmFja2dyb3VuZCIsImJhY2tncm91bmROYW1lIjoiQmxpenphcmQgVG9vbHRpcCIsInJlc291cmNlQmFyIjoiSW50ZXJmYWNlXFxBZGRvbnNcXFNoYXJlZE1lZGlhXFxzdGF0dXNiYXJcXEFybW9yeSJ9LCJhdWRpbyI6eyJzdGFyd2VhdmVyc1JlYWR5Ijp7ImVuYWJsZWQiOmZhbHNlLCJzb3VuZE5hbWUiOiJUUkI6IEJveGluZyBBcmVuYSBHb25nIiwibmFtZSI6IlN0YXJ3ZWF2ZXIgUmVhZHkiLCJzb3VuZCI6IkludGVyZmFjZVxcQWRkb25zXFxUd2ludG9wSW5zYW5pdHlCYXJcXFNvdW5kc1xcQm94aW5nQXJlbmFTb3VuZC5vZ2cifSwib3ZlcmNhcCI6eyJlbmFibGVkIjpmYWxzZSwic291bmROYW1lIjoiVFJCOiBBaXIgSG9ybiIsIm5hbWUiOiJPdmVyY2FwIiwic291bmQiOiJJbnRlcmZhY2VcXEFkZG9uc1xcVHdpbnRvcEluc2FuaXR5QmFyXFxTb3VuZHNcXEFpckhvcm4ub2dnIn0sInNmUmVhZHkiOnsiZW5hYmxlZCI6ZmFsc2UsInNvdW5kTmFtZSI6IlRSQjogQm94aW5nIEFyZW5hIEdvbmciLCJuYW1lIjoiU3RhcmZhbGwgUmVhZHkiLCJzb3VuZCI6IkludGVyZmFjZVxcQWRkb25zXFxUd2ludG9wSW5zYW5pdHlCYXJcXFNvdW5kc1xcQm94aW5nQXJlbmFTb3VuZC5vZ2cifSwic3NSZWFkeSI6eyJlbmFibGVkIjpmYWxzZSwic291bmROYW1lIjoiVFJCOiBCb3hpbmcgQXJlbmEgR29uZyIsIm5hbWUiOiJTdGFyc3VyZ2UgUmVhZHkiLCJzb3VuZCI6IkludGVyZmFjZVxcQWRkb25zXFxUd2ludG9wSW5zYW5pdHlCYXJcXFNvdW5kc1xcQm94aW5nQXJlbmFTb3VuZC5vZ2cifX0sInRocmVzaG9sZHMiOnsic3RhcnN1cmdlVGhyZXNob2xkT25seU92ZXJTaG93IjpmYWxzZSwic3RhcmZhbGwiOnsiZW5hYmxlZCI6ZmFsc2V9LCJpY29ucyI6eyJlbmFibGVkIjpmYWxzZSwicmVsYXRpdmVUbyI6IkJPVFRPTSIsInhQb3MiOjAsImJvcmRlciI6Miwid2lkdGgiOjI0LCJyZWxhdGl2ZVRvTmFtZSI6IkJlbG93Iiwic2hvd0Nvb2xkb3duIjp0cnVlLCJoZWlnaHQiOjI0LCJ5UG9zIjoxMiwiZGVzYXR1cmF0ZWQiOnRydWV9LCJ3aWR0aCI6Miwib3V0T2ZSYW5nZSI6dHJ1ZSwib3ZlcmxhcEJvcmRlciI6dHJ1ZSwic3RhcnN1cmdlMyI6eyJlbmFibGVkIjpmYWxzZX0sInN0YXJzdXJnZTIiOnsiZW5hYmxlZCI6dHJ1ZX0sInN0YXJzdXJnZSI6eyJlbmFibGVkIjp0cnVlfX0sImRpc3BsYXlUZXh0Ijp7ImRlZmF1bHQiOnsiZm9udEZhY2UiOiJJbnRlcmZhY2VcXEFkZG9uc1xcU2hhcmVkTWVkaWFfTXlNZWRpYVxcZm9udFxcMjkzMi50dGYiLCJjb2xvciI6IkZGRkZGRkZGIiwiZm9udEp1c3RpZnlIb3Jpem9udGFsIjoiTEVGVCIsImZvbnRTaXplIjoxOCwiZm9udEp1c3RpZnlIb3Jpem9udGFsTmFtZSI6IkxlZnQiLCJmb250RmFjZU5hbWUiOiIyOTMyIn0sImJhclRleHQiOlt7InVzZURlZmF1bHRGb250Q29sb3IiOmZhbHNlLCJmb250RmFjZSI6IkludGVyZmFjZVxcQWRkb25zXFxTaGFyZWRNZWRpYV9NeU1lZGlhXFxmb250XFwyOTMyLnR0ZiIsInVzZURlZmF1bHRGb250RmFjZSI6ZmFsc2UsImd1aWQiOiI4NGNjZmM3Yy03NzkwLTRlNDYtODgyYi1jMDI5ZGY5OTkxZmYiLCJmb250SnVzdGlmeUhvcml6b250YWxOYW1lIjoiTGVmdCIsInRleHQiOiIkaGFzdGUlIiwiZW5hYmxlZCI6dHJ1ZSwiZm9udEZhY2VOYW1lIjoiMjkzMiIsIm5hbWUiOiJMZWZ0IiwicG9zaXRpb24iOnsicmVsYXRpdmVUb05hbWUiOiJMZWZ0IiwicmVsYXRpdmVUbyI6IkxFRlQiLCJ4UG9zIjoyLCJyZWxhdGl2ZVRvRnJhbWVOYW1lIjoiTWFpbiBSZXNvdXJjZSBCYXIiLCJ5UG9zIjowLCJyZWxhdGl2ZVRvRnJhbWUiOiJSZXNvdXJjZSJ9LCJmb250SnVzdGlmeUhvcml6b250YWwiOiJMRUZUIiwidXNlRGVmYXVsdEZvbnRTaXplIjpmYWxzZSwiY29sb3IiOiJGRkZGRkZGRiIsImZvbnRTaXplIjoyNX0seyJ1c2VEZWZhdWx0Rm9udENvbG9yIjpmYWxzZSwiZm9udEZhY2UiOiJJbnRlcmZhY2VcXEFkZG9uc1xcU2hhcmVkTWVkaWFfTXlNZWRpYVxcZm9udFxcMjkzMi50dGYiLCJ1c2VEZWZhdWx0Rm9udEZhY2UiOmZhbHNlLCJndWlkIjoiMzJjMzkwM2ItNWY3Zi00MTg1LTk5ZjctZTYyMTIyNWFiZGEyIiwiZm9udEp1c3RpZnlIb3Jpem9udGFsTmFtZSI6IkNlbnRlciIsInRleHQiOiIkZWNsaXBzZVRpbWUiLCJlbmFibGVkIjp0cnVlLCJmb250RmFjZU5hbWUiOiIyOTMyIiwibmFtZSI6Ik1pZGRsZSIsInBvc2l0aW9uIjp7InJlbGF0aXZlVG9OYW1lIjoiQ2VudGVyIiwicmVsYXRpdmVUbyI6IkNFTlRFUiIsInhQb3MiOjAsInJlbGF0aXZlVG9GcmFtZU5hbWUiOiJNYWluIFJlc291cmNlIEJhciIsInlQb3MiOjAsInJlbGF0aXZlVG9GcmFtZSI6IlJlc291cmNlIn0sImZvbnRKdXN0aWZ5SG9yaXpvbnRhbCI6IkNFTlRFUiIsInVzZURlZmF1bHRGb250U2l6ZSI6ZmFsc2UsImNvbG9yIjoiRkZGRkZGRkYiLCJmb250U2l6ZSI6MjV9LHsidXNlRGVmYXVsdEZvbnRDb2xvciI6ZmFsc2UsImZvbnRGYWNlIjoiSW50ZXJmYWNlXFxBZGRvbnNcXFNoYXJlZE1lZGlhX015TWVkaWFcXGZvbnRcXDI5MzIudHRmIiwidXNlRGVmYXVsdEZvbnRGYWNlIjp0cnVlLCJndWlkIjoiODRlNjQzYjMtOTUzMi00N2ZiLTk2YTYtODYwMjdkMTFlNTY4IiwiZm9udEp1c3RpZnlIb3Jpem9udGFsTmFtZSI6IlJpZ2h0IiwidGV4dCI6IiRjYXN0aW5nKyRwYXNzaXZlICRhc3RyYWxQb3dlclRvdGFsIiwiZW5hYmxlZCI6dHJ1ZSwiZm9udEZhY2VOYW1lIjoiMjkzMiIsIm5hbWUiOiJSaWdodCIsInBvc2l0aW9uIjp7InJlbGF0aXZlVG9OYW1lIjoiUmlnaHQiLCJyZWxhdGl2ZVRvIjoiUklHSFQiLCJ4UG9zIjotMiwicmVsYXRpdmVUb0ZyYW1lTmFtZSI6Ik1haW4gUmVzb3VyY2UgQmFyIiwieVBvcyI6MCwicmVsYXRpdmVUb0ZyYW1lIjoiUmVzb3VyY2UifSwiZm9udEp1c3RpZnlIb3Jpem9udGFsIjoiUklHSFQiLCJ1c2VEZWZhdWx0Rm9udFNpemUiOmZhbHNlLCJjb2xvciI6IkZGRkZGRkZGIiwiZm9udFNpemUiOjI1fV19LCJkaXNwbGF5QmFyIjp7ImFsd2F5c1Nob3ciOnRydWUsIm5vdFplcm9TaG93IjpmYWxzZSwiZHJhZ29ucmlkaW5nIjp0cnVlLCJuZXZlclNob3ciOmZhbHNlfSwiY29sb3JzIjp7InRocmVzaG9sZCI6eyJvdXRPZlJhbmdlIjoiRkY0NDAwMDAiLCJzdGFyZmFsbFBhbmRlbWljIjoiRkY4QjAwMDAiLCJvdmVyIjoiRkYwMEZGMDAiLCJ1bmRlciI6IkZGRkZGRkZGIn0sInRleHQiOnsiZG90cyI6eyJlbmFibGVkIjp0cnVlLCJwYW5kZW1pYyI6IkZGRkZGRjAwIiwiZG93biI6IkZGRkYwMDAwIiwidXAiOiJGRkZGRkZGRiJ9LCJjdXJyZW50IjoiRkZGRkI2NjgiLCJvdmVyVGhyZXNob2xkIjoiRkYwMEZGMDAiLCJvdmVyVGhyZXNob2xkRW5hYmxlZCI6ZmFsc2UsIm92ZXJjYXAiOiJGRkZGMDAwMCIsImNhc3RpbmciOiJGRkZGRkZGRiIsIm92ZXJjYXBFbmFibGVkIjp0cnVlLCJwYXNzaXZlIjoiRkYwMEFBMDAifSwiYmFyIjp7ImVjbGlwc2UxR0NEIjoiRkZGRjAwMDAiLCJvdmVyY2FwRW5hYmxlZCI6dHJ1ZSwiY2VsZXN0aWFsIjoiRkY0QTk1Q0UiLCJmbGFzaEVuYWJsZWQiOmZhbHNlLCJib3JkZXJPdmVyY2FwIjoiRkZGRjAwMDAiLCJzb2xhciI6IkZGRkZFRTAwIiwiYm9yZGVyIjoiRkZDMTY5MjAiLCJmbGFzaFBlcmlvZCI6MCwiZmxhc2hTc0VuYWJsZWQiOnRydWUsInBhc3NpdmUiOiJGRjAwNjYwMCIsIm1vb25raW5Gb3JtTWlzc2luZyI6IkZGRkYwMDAwIiwiY2FzdGluZyI6IkZGRkZGRkZGIiwiZmxhc2hBbHBoYSI6MC43LCJiYWNrZ3JvdW5kIjoiNjYwMDAwMDAiLCJiYXNlIjoiRkZGRjdDMEEiLCJsdW5hciI6IkZGMTQ0RDcyIn19LCJyZXNvdXJjZVByZWNpc2lvbiI6MCwib3ZlcmNhcCI6eyJtb2RlIjoiZml4ZWQiLCJmaXhlZCI6MTAwLCJyZWxhdGl2ZSI6MH0sImhhc3RlUHJlY2lzaW9uIjoyLCJlbmRPZkVjbGlwc2UiOnsiZW5hYmxlZCI6dHJ1ZSwiY2VsZXN0aWFsQWxpZ25tZW50T25seSI6ZmFsc2UsIm1vZGUiOiJ0aW1lIiwidGltZU1heCI6MywiZ2Nkc01heCI6Mn0sImJhciI6eyJ4UG9zIjowLCJzaG93UGFzc2l2ZSI6dHJ1ZSwiYm9yZGVyIjowLCJ3aWR0aCI6MzQ4LCJzaG93Q2FzdGluZyI6dHJ1ZSwiaGVpZ2h0IjozNCwieVBvcyI6LTE3OCwicGluVG9QZXJzb25hbFJlc291cmNlRGlzcGxheSI6ZmFsc2UsImRyYWdBbmREcm9wIjpmYWxzZX19fX0=

**Comment by Twintop** [comment]
OK, I've found the source of the problem. The good news is you can adjust it without me needing to get a proper fix out. It looks like the flash period for Starsurge is set to 0, which is leading to a divide by 0 error under the hood. If you change this to some other value you should be OK.
![image](https://github.com/user-attachments/assets/90ecbf08-16e3-4716-bd1e-f10ac71f0764)

I'll get a fix out to sanity check this and prevent it from being 0.

**Comment by KareiTV** [comment]
Absolute legend! That did indeed solve the problem alright. Was wondering why it only showed up on this specific loadout and not another. Many thanks!
