### ISSUE TITLE
Opacity slider is reversed

### ISSUE THREAD

**Issue by layday** [Twintop/TwintopInsanityBar#67]
I tried fiddling with the colours of the new balance druid module when I noticed that pulling the slider all way up made the colour transparent:

![slider](https://user-images.githubusercontent.com/31134424/97123219-63332800-1733-11eb-9508-bfa23c4618e9.gif)

This should be the other way around.  I assume the slider returns `0` for opaque and `1` for fully transparent so you'd have to subtract the value from 1 before operating on it.

**Comment by Twintop** [comment]
Thanks for bringing this up. I've got another bug open about this (#40) but I'm going to mark that one as a duplicate instead of this one because of the GIF. :D

**Comment by layday** [comment]
whoops, I should've searched before opening a new bug!

**Comment by Twintop** [comment]
No worries! I'd rather have duplicates to sort through than bugs to go unreported! 😄
