### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by Twintop** [Twintop/TwintopInsanityBar#8]
**Localization Google Sheet**
https://docs.google.com/spreadsheets/d/1ICs-ZR3KeySXXD268xNUqzkc9Eqi0bXhjISUL0AoPRQ/edit?usp=sharing

Status by file (that has localizable strings within it):

**Shared**
- [x] Init.lua
- [x] Classes\Target.lua
- [x] Functions\BarText.lua
- [x] Functions\LibSharedMedia.lua
- [x] Functions\News.lua
- [x] Functions\Threshold.lua
- [x] Options\OptionsUi.lua
- [x] Options\Options.lua

**Class Implementations**
- [x] ClassModules\DemonHunter.lua
- [x] ClassModules\Druid.lua
- [x] ClassModules\Evoker.lua
- [x] ClassModules\Hunter.lua
- [x] ClassModules\Monk.lua
- [x] ClassModules\Priest.lua
- [x] ClassModules\Rogue.lua
- [x] ClassModules\Shaman.lua
- [x] ClassModules\Warrior.lua

**Class Options Menus**
- [x] ClassModules\Options\DemonHunterOptions.lua
- [x] ClassModules\Options\DruidOptions.lua
- [x] ClassModules\Options\EvokerOptions.lua
- [x] ClassModules\Options\HunterOptions.lua
- [x] ClassModules\Options\MonkOptions.lua
- [x] ClassModules\Options\PriestOptions.lua
- [x] ClassModules\Options\RogueOptions.lua
- [x] ClassModules\Options\ShamanOptions.lua
- [x] ClassModules\Options\WarriorOptions.lua

**Original content:**
xy985426 on CurseForge requests:

Please add a localization file  thank you

**Comment by LucasCH13** [comment]
Hey Twintop, i'm interested in participating for the french translation, is there specific things i need to know before ?

**Comment by Twintop** [comment]
@LucasCH13 Hi there, thanks for being interested in helping translate the addon!

What I'll be doing is sharing some files that contain translations (from English) that need to be made. Probably, I'll have them present in a Google Sheet with the English version in one column and translations in subsequent columns. I'll take that spreadsheet and have a process to automagically spit out/fill in the Lua locale files.

I'm working through getting all of the strings converted over to be able to be used for localization right now and likely won't have a file ready to work on for a week or so (depending on IRL).

**Comment by Twintop** [comment]
Actually, there is one thing to be aware of that I don't want to forget to mention. WoW's text rending has some pretty handy built in language escape sequences, including one that might be useful for French -- https://warcraft.wiki.gg/wiki/UI_escape_sequences#French . I'm using the `|5` escape for a/an in a couple of places.

**Comment by Twintop** [comment]
All strings within the addon are now localizable.
